## **EDA ANALYSIS** (РАЗВЕДОЧНЫЙ АНАЛИЗ)

Тема: первичный разведочный анализ датасета *"FMCG Sales & Profit Dataset (2023–2025)"* для дальнейшей коммерческой аналитики

In [2]:
# Импорт нужных библиотек
import pandas as pd
import matplotlib.pyplot as plt

# Стиль для графиков
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
plt.style.use('seaborn-v0_8-whitegrid')

In [3]:
# Загрузка данных
df = pd.read_csv('../data/raw-data/fmcg_sales_marketing_profitability_2023_2025.csv')
df.head()

,Order_ID,Order_Date,Year,Quarter,Month,Month_Name,Region,Country,City,Sales_Person,Customer_Type,Sales_Channel,Promotion_Type,Product_Category,Brand,Product_Name,SKU,Units_Sold,Unit_Price_USD,Discount_Pct,Gross_Sales_USD,Marketing_Spend_USD,COGS_USD,Logistics_Cost_USD,Net_Revenue_USD,Profit_USD,Profit_Margin_Pct
0,FMCG-2025-000001,2025-09-26,2025,Q3,9,September,Oceania,Australia,Perth,Ethan Cole,B2C,Modern Trade,Seasonal Campaign,Personal Care,PureLiva,Shampoo Repair,PCR-PL-101,73,8.47,8.94,618.31,66.05,314.09,43.03,563.03,139.86,24.84
1,FMCG-2024-000002,2024-10-09,2024,Q4,10,October,Asia,India,Mumbai,Meera Nair,B2C,Online,Bundle Offer,Personal Care,BrightSmile,Toothpaste Mint,PCR-BS-301,99,2.89,9.86,286.11,35.26,123.79,23.89,257.90,74.96,29.07
2,FMCG-2024-000003,2024-07-06,2024,Q3,7,July,North America,USA,Los Angeles,Nina Booker,B2B,Distributor,Seasonal Campaign,Personal Care,FreshNest,Body Wash Citrus,PCR-FN-201,361,5.96,15.32,2151.56,171.46,1011.60,107.02,1821.94,531.86,29.19
3,FMCG-2024-000004,2024-05-25,2024,Q2,5,May,Europe,France,Paris,Oliver Kent,B2B,Wholesale,No Promo,Snacks,NutriBite,Protein Bar Peanut,SNK-NB-202,603,3.80,18.00,2291.40,118.39,1133.66,85.20,1878.95,541.70,28.83
4,FMCG-2023-000005,2023-08-10,2023,Q3,8,August,Europe,France,Lyon,Lucas Bennett,B2C,Modern Trade,Loyalty Cashback,Dairy & Breakfast,FarmJoy,Greek Yogurt Plain,DBF-FJ-202,113,3.18,12.46,359.34,34.82,157.70,23.02,314.57,99.03,31.48

In [4]:
# Получение общей информации о датафрейме
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18240 entries, 0 to 18239
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Order_ID             18240 non-null  str
 1   Order_Date           18240 non-null  str
 2   Year                 18240 non-null  int64
 3   Quarter              18240 non-null  str
 4   Month                18240 non-null  int64
 5   Month_Name           18240 non-null  str
 6   Region               18240 non-null  str
 7   Country              18240 non-null  str
 8   City                 18240 non-null  str
 9   Sales_Person         18240 non-null  str
 10  Customer_Type        18240 non-null  str
 11  Sales_Channel        18240 non-null  str
 12  Promotion_Type       18240 non-null  str
 13  Product_Category     18240 non-null  str
 14  Brand                18240 non-null  str
 15  Product_Name         18240 non-null  str
 16  SKU                  18240 non-null  str
 17  Units_Sold           18240 non-null  int64
 18  Unit_Price_USD       18240 non-null  float64
 19  Discount_Pct         18240 non-null  float64
 20  Gross_Sales_USD      18240 non-null  float64
 21  Marketing_Spend_USD  18240 non-null  float64
 22  COGS_USD             18240 non-null  float64
 23  Logistics_Cost_USD   18240 non-null  float64
 24  Net_Revenue_USD      18240 non-null  float64
 25  Profit_USD           18240 non-null  float64
 26  Profit_Margin_Pct    18240 non-null  float64
dtypes: float64(9), int64(3), str(15)
memory usage: 3.8 MB

In [5]:
# Проверка на пропущенные значения
missing_values = df.isnull().sum()  # Подсчет пропущенных значений в каждом столбце
missing_values = missing_values[missing_values > 0].reset_index().rename(columns={'index': 'Column', 0: 'Missing Values'})  # Фильтрация и переименование столбцов
if missing_values.empty:
    print("\033[1m" + '- ПРОПУСКОВ В ДАННЫХ НЕ ОБНАРУЖЕНО!' + "\033[1m")
else:
    display(missing_values)

- ПРОПУСКОВ В ДАННЫХ НЕ ОБНАРУЖЕНО!

In [6]:
# Проверка на дубликаты в данных
duplicate_count = df.duplicated().sum()
if duplicate_count == 0:
    print("\033[1m" + '- ДУБЛИКАТОВ В ДАННЫХ НЕ ОБНАРУЖЕНО!')
else:
    print(duplicate_count)
print()

- ДУБЛИКАТОВ В ДАННЫХ НЕ ОБНАРУЖЕНО!

In [7]:
# Определение периода, охватываемого данными
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

start = df["Order_Date"].min()
end = df["Order_Date"].max()
years = (end - start).days / 365.25

print(
    f"Данные охватывают период с {start.date()} по {end.date()}. "
    f"Продолжительность — примерно {years:.1f} года."
)

Данные охватывают период с 2023-01-01 по 2025-12-31. Продолжительность — примерно 3.0 года.

In [8]:
geo_summary = df.groupby([df.Region, df.Country]).agg({'City': 'nunique', 'Sales_Person': 'nunique'}).reset_index()
print(f'Данные охватывают {df.Region.nunique()} региона, {df.Country.nunique()} стран, {df.City.nunique()} городов и {df.Sales_Person.nunique()} торговых представителей.')
geo_summary

Данные охватывают 5 региона, 17 стран, 48 городов и 36 торговых представителей.

           Region      Country  City  Sales_Person
0            Asia        India     4             8
1            Asia    Indonesia     2             8
2            Asia     Thailand     2             8
3            Asia          UAE     2             8
4          Europe       France     3             8
5          Europe      Germany     3             8
6          Europe        Italy     3             8
7          Europe        Spain     3             8
8          Europe           UK     3             8
9   North America       Canada     3             8
10  North America       Mexico     3             8
11  North America          USA     5             8
12        Oceania    Australia     4             6
13        Oceania  New Zealand     2             6
14  South America       Brazil     2             6
15  South America        Chile     2             6
16  South America     Colombia     2             6

In [9]:
print(f'Данные охватывают {df.Product_Category.nunique()} категорий продуктов, {df.Brand.nunique()} брендов продуктов и самих {df.Product_Name.nunique()} уникальных продуктов.')

Данные охватывают 5 категорий продуктов, 17 брендов продуктов и самих 30 уникальных продуктов.

In [25]:
print(f'В данных представлено {df.Customer_Type.nunique()} типа клиентов, {df.Sales_Channel.nunique()} канала продаж и {df.Promotion_Type.nunique() - 1} различных типов промо-акций (Также значение "No Promo").')

В данных представлено 2 типа клиентов, 4 канала продаж и 6 различных типов промо-акций (Также значение "No Promo").

In [52]:
# Денежные показатели
gross_sales = df.Gross_Sales_USD.sum()
net_revenue = df.Net_Revenue_USD.sum()
units_sold = df.Units_Sold.sum()
discount_load = (1 - net_revenue / gross_sales) * 100 if gross_sales != 0 else 0
marketing_spend = df.Marketing_Spend_USD.sum()
logistics_cost = df.Logistics_Cost_USD.sum()
COGS = df.COGS_USD.sum()
profit = net_revenue - (marketing_spend + logistics_cost + COGS)
profit_margin = profit / net_revenue * 100 if net_revenue != 0 else 0

print(f'\nВаловая выручка ${gross_sales:_}'.replace('_', ' '),
      f'\nСкидочная нагрузка {discount_load:.2f}%, потрачено ${gross_sales - net_revenue:,.2f} на скидки'.replace(',', ' '),
      f'\nВыручка после скидок ${net_revenue:,.2f}'.replace(',', ' '),
      f'\nМаркетинговые расходы ${marketing_spend:,.2f} ({marketing_spend / net_revenue * 100:,.2f}% от выручки после скидок)'.replace(',', ' '),
      f'\nЛогистические расходы ${logistics_cost:,.2f} ({logistics_cost / net_revenue * 100:,.2f}% от выручки после скидок)'.replace(',', ' '),
      f'\nCOGS ${COGS:,.2f} ({COGS / net_revenue * 100:,.2f}% от выручки после скидок)'.replace(',', ' '),
      f'\nПрибыль ${profit:,.2f}, маржинальность {profit_margin:.2f}%'.replace(',', ' '),
      f'\nПродано единиц {units_sold:,}'.replace(',', ' ')
)

Валовая выручка $17 080 515.05
Скидочная нагрузка 15.40%  потрачено $2 630 595.05 на скидки
Выручка после скидок $14 449 920.00
Маркетинговые расходы $1 563 932.03 (10.82% от выручки после скидок)
Логистические расходы $985 539.83 (6.82% от выручки после скидок)
COGS $8 591 482.83 (59.46% от выручки после скидок)
Прибыль $3 308 965.31  маржинальность 22.90%
Продано единиц 3 883 474